name: Build and Deploy Docker to Azure Web App

on:
  push:
    branches:
      - main   # Or your deployment branch (like lp_uae)
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Log in to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and Push Docker image
    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/uae-lpr:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/uae-lpr:latest

    # Azure Login (make sure you have these secrets set!)
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'lp'                        # Your Azure Web App name
        slot-name: 'Production'               # Usually 'Production'
        images: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/uae-lpr:latest'
