name: Build and Deploy Docker to Azure Web App

on:
  push:
    branches:
      - main      # Change to your branch if not using 'main'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/uae-lpr:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/uae-lpr:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lp'
          slot-name: 'Production'
          images: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/uae-lpr:latest'
